### PR TITLE
WIP: Simplify code by:

### PR DESCRIPTION
**Pull request by maxandersen**
a) move to use picocoli for command line parsing
b) remove unncessary external classes
c) make it runnable as a jbang script
d) fix parsing so it does not fail on repo urls like https://github.com/starfixdev/starfix
e) make command launching use actual directory rather than the parent

related to #49

### CODE REVIEW

**Comment by fahad-israr** [comment]
@maxandersen any idea why the build failed?
unfortunately, the gh-actions logs have expired :(

**Comment by fahad-israr** [comment]
@maxandersen   I've tried to update the Actions and now I am merging your PR. Even if the Build fails I'll rectify and try to make it work .

**Comment by maxandersen** [comment]
ok - fyi for next similar happens - you could just do the build locally or done a commit to this pr or used it for another PR and it would have ran the build.

**Comment by fahad-israr** [comment]
> ok - fyi for next similar happens - you could just do the build locally or done a commit to this pr or used it for another PR and it would have ran the build.

sure :+1:

**Pull request merged**
