### PR TITLE
Fixed installer directory structure for windows

### PR DESCRIPTION
**Pull request by fahad-israr**
- moved `starfix.cmd` to `Starfix sub-directory` which would then be moved to the user's home directory.
- Tested to work on win-64

### CODE REVIEW

**Comment by fahad-israr** [comment]
Referencing the Issue:https://github.com/starfixdev/starfix/issues/31

**Comment by maxandersen** [comment]
in the .reg file we still refer to "Starfish" not "Starfix"

that should be fixed too, right ?

**Comment by maxandersen** [comment]
and while we are add it, I suggest we just keep lowercase "starfix" instead of "Starfix" on all platforms.

**Comment by fahad-israr** [comment]
- Made the suggested changes
- renamed Starfix->starfix
- tested again on windows 10 64 bit

**Pull request merged**
