### PR TITLE
Added picocli code-gen

### PR DESCRIPTION
**Pull request by fahad-israr**
Trying to Resolve Issue: https://github.com/starfixdev/starfix/issues/83

### CODE REVIEW

**Comment by fahad-israr** [comment]
@maxandersen This PR resolves https://github.com/starfixdev/starfix/issues/83
I've tried running the generated native binary and it works now .

**Comment by fahad-israr** [comment]
@maxandersen The Linked issue is resolved but I am  facing another issue now.
 I am facing  issue with `starfic config ` command. 
When I run it in development mode using `./mvnw compile quarkus:dev -Dquarkus.args="config"` it works fine.
But when I run the native binary (Native Executable ) it shows warning to me and the config properties aren't read in the app.
`WARN - could not read defaults from /Users/devfi/.config/starfix.yaml: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.Properties` (no Creators, like default constructor, exist): no default constructor found
 at [Source: (File); line: 2, column: 1]`

- How to reproduce issue?  Download artifact from any of the latest gh-actions build (you can use this one : https://github.com/starfixdev/starfix/actions/runs/1107837415) . Then run `./starfix config` (Note: Normally macOS X won't startup the app if u run directlt from cli as it won't trust it. firstly run from the finder and then run from cli )

**Comment by maxandersen** [comment]
I can't imagine why we would need to add the picocli annotation processor to "fix"  #83 that sounds more like an "accidental" fix.

**Comment by maxandersen** [comment]
What made you think the annotation processor would help ?

**Comment by maxandersen** [comment]
so same solution as last is to add `@RegisterForReflection` on the class having issues.

reason it fixes it is that the annotation processor is apparently doing more than Quarkus picocli integration does. opened https://github.com/quarkusio/quarkus/issues/19289 to get it fixed there.

**Comment by maxandersen** [comment]
opened #87 for "right" fix.

**Pull request closed without merging**
